### PR TITLE
Lab09 Pull Request

### PR DESCRIPTION
**Pull request by jmangel**
Hi Ally, this pull request fixes issue #15. This took us about 4.5 hours to complete, as we ran into quite a few unexpected issues.

### CODE REVIEW

**Comment by jmangel** [comment]
Uses disk storage to save data between sessions, fixing issue #25

**Comment by jmangel** [comment]
closes font/color selection window when something is selected. Fixes issue #20 .

**Comment by jmangel** [comment]
fixes #26 by implementing persistence functionality (including writing to/reading from disk) in the Combined translator

**Comment by jmangel** [comment]
fixes issue #13 and revisits issue #20 by doing the following:
*allows stacking of font styles
*adds Times New Roman option
*adds "Apply" button that closes the window

**Comment by jmangel** [comment]
automatically selects PigToEng translation where there is only one valid option, fixing #30

**Comment by jmangel** [comment]
makes close button in Help screen of combined translator to be consistent with font style

**Comment by FrostyNarwhal** [comment]
Updated README.md and added W16_Lab10.md with a list of issues

**Pull request merged**
